#!/usr/bin/env python3
"""Generate src/mod/fh1_symbols.inc, the mod symbol table (NP-7.2).

Reads config/mod/fh1-symbols.toml (semantic symbols and offsets) and every
[[midasm_hook]] of config/rexglue/analysis/main-xex.toml (as hook.<name>),
and writes a sorted C++ table. With --check, fails when the checked-in file
differs from what would be generated. With --v4, writes fh1_symbols_v4.inc for
the title-update build: hook addresses come from config/rexglue/analysis-v4
and semantic symbols are mapped by tools/map-fh1-v4-addresses.py. Field
offsets come from config/mod/fh1-offsets-v4.toml, which must list every
offset with its verified v4 value (docs/TITLE_UPDATE_V4_BACKLOG.md TU-4).
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYMBOLS = ROOT / "config" / "mod" / "fh1-symbols.toml"
HOOKS = ROOT / "config" / "rexglue" / "analysis" / "main-xex.toml"
OUTPUT = ROOT / "src" / "mod" / "fh1_symbols.inc"
V4_HOOKS = ROOT / "config" / "rexglue" / "analysis-v4" / "main-xex.toml"
V4_OUTPUT = ROOT / "src" / "mod" / "fh1_symbols_v4.inc"
V4_OFFSETS = ROOT / "config" / "mod" / "fh1-offsets-v4.toml"
V4_EXECUTABLE = ("default.xex+default.xexp", "74B033805AB1BCAA")  # verified v4 image SHA-256 prefix


def map_v4(addresses: dict[str, int]) -> dict[str, int]:
    import importlib.util
    spec = importlib.util.spec_from_file_location("v4map", ROOT / "tools/map-fh1-v4-addresses.py")
    v4map = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(v4map)
    images = ROOT / ".local/game/v4-images"
    mapper = v4map.Mapper(v4map.Image((images / "default.base.bin").read_bytes(), 0x82000000),
                          v4map.Image((images / "default.v4.bin").read_bytes(), 0x82000000))
    overrides = {int(k, 16): int(v, 16) for k, v in tomllib.loads(
        (ROOT / "config/rexglue/analysis-v4/overrides.toml").read_text(encoding="utf-8")).get("default", {}).items()}
    mapped, missing = {}, []
    for name, address in addresses.items():
        if address in overrides:
            mapped[name] = overrides[address]
            continue
        target, _ = mapper.map(address, "code", 16)
        if target is None:
            target, _ = mapper.map(address, "data")
        if target is None:
            missing.append(f"{name} 0x{address:08X}")
        else:
            mapped[name] = target
    if missing:
        raise ValueError("symbols without a v4 mapping: " + ", ".join(missing))
    return mapped


def generate(v4: bool = False) -> str:
    symbols = tomllib.loads(SYMBOLS.read_text(encoding="utf-8"))
    hooks = tomllib.loads((V4_HOOKS if v4 else HOOKS).read_text(encoding="utf-8")).get("midasm_hook", [])
    entries: dict[str, int] = {}
    semantic = {name: int(address) for name, address in symbols["symbols"].items()}
    for name, address in (map_v4(semantic) if v4 else semantic).items():
        entries[name] = address
    for hook in hooks:
        name = "hook." + hook["name"]
        if name in entries and entries[name] != int(hook["address"]):
            raise ValueError(f"{name} has two addresses")
        entries[name] = int(hook["address"])
    executable, sha256 = V4_EXECUTABLE if v4 else (symbols["executable"], symbols["sha256"])
    lines = [
        "// Generated by tools/generate-fh1-symbols.py from config/mod/fh1-symbols.toml",
        f"// and config/rexglue/{'analysis-v4' if v4 else 'analysis'}/main-xex.toml. Do not edit.",
        f"// Executable: {executable} {sha256}",
        "",
        "PINYON_SYMBOL_EXECUTABLE(\"%s\", \"%s\")" % (executable, sha256),
    ]
    for name in sorted(entries):
        lines.append(f'PINYON_SYMBOL("{name}", 0x{entries[name]:08X})')
    offsets = {name: int(value) for name, value in symbols["offsets"].items()}
    if v4:
        verified = tomllib.loads(V4_OFFSETS.read_text(encoding="utf-8"))["offsets"]
        if set(verified) != set(offsets):
            raise ValueError(f"{V4_OFFSETS.name} must list exactly the offsets of {SYMBOLS.name}: "
                             f"missing {sorted(set(offsets) - set(verified))}, "
                             f"extra {sorted(set(verified) - set(offsets))}")
        offsets = {name: int(value) for name, value in verified.items()}
    for name in sorted(offsets):
        note = ("  // verified on v4" if offsets[name] == int(symbols["offsets"][name])
                else f"  // verified on v4; base {int(symbols['offsets'][name])}") if v4 else ""
        lines.append(f'PINYON_OFFSET("{name}", {offsets[name]}){note}')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--v4", action="store_true", help="generate the title-update table")
    args = parser.parse_args()
    global OUTPUT
    if args.v4:
        OUTPUT = V4_OUTPUT
    text = generate(args.v4)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run tools/generate-fh1-symbols.py")
            return 1
        print("symbol table is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
