#!/usr/bin/env python3
"""Generate src/fh1_v4_addresses.inc, the base -> v4 table behind FH1_ADDR.

Scans src/ for FH1_ADDR(0x........u) uses and maps each base-disc address to
the v4 title update with tools/map-fh1-v4-addresses.py: code addresses (inside
an executable section) through function matching and validated context, data
addresses through lis/addi pairs at the same instruction in matched code.
Manually researched pairs come from config/rexglue/analysis-v4/overrides.toml
[default]. Exits 1 and writes nothing if any address is unmapped.
"""
from __future__ import annotations

import argparse
import importlib.util
import re
import struct
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("v4map", ROOT / "tools/map-fh1-v4-addresses.py")
V4MAP = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(V4MAP)
PORT_SPEC = importlib.util.spec_from_file_location("v4port", ROOT / "tools/port-fh1-v4-analysis.py")
PORT = importlib.util.module_from_spec(PORT_SPEC)
PORT_SPEC.loader.exec_module(PORT)

USE = re.compile(r"FH1_ADDR\(0x([0-9A-Fa-f]{8})u?\)")
OUTPUT = ROOT / "src/fh1_v4_addresses.inc"


def executable_ranges(image: bytes, load: int) -> list[tuple[int, int]]:
    pe = struct.unpack_from("<I", image, 0x3C)[0]
    count = struct.unpack_from("<H", image, pe + 6)[0]
    optional = struct.unpack_from("<H", image, pe + 20)[0]
    ranges = []
    for i in range(count):
        section = pe + 24 + optional + i * 40
        size, rva = struct.unpack_from("<II", image, section + 8)
        characteristics = struct.unpack_from("<I", image, section + 36)[0]
        if characteristics & 0x20000000:
            ranges.append((load + rva, load + rva + size))
    return ranges


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--images", type=Path, default=ROOT / ".local/game/v4-images")
    parser.add_argument("--check", action="store_true", help="fail if the committed table is stale")
    args = parser.parse_args()
    uses = set()
    for path in sorted((ROOT / "src").rglob("*")):
        if path.suffix in (".cpp", ".h", ".inc"):
            uses.update(int(m.group(1), 16) for m in USE.finditer(path.read_text(encoding="utf-8")))
    base = (args.images / "default.base.bin").read_bytes()
    mapper = V4MAP.Mapper(V4MAP.Image(base, 0x82000000),
                          V4MAP.Image((args.images / "default.v4.bin").read_bytes(), 0x82000000))
    code = executable_ranges(base, 0x82000000)
    overrides_path = ROOT / "config/rexglue/analysis-v4/overrides.toml"
    overrides = {int(k, 16): int(v, 16) for k, v in
                 tomllib.loads(overrides_path.read_text(encoding="utf-8")).get("default", {}).items()}
    rows, unmapped = [], []
    for address in sorted(uses):
        is_code = any(lo <= address < hi for lo, hi in code)
        if address in overrides:
            mapped, method = overrides[address], "override"
        elif is_code:
            mapped, method = mapper.map(address, "code", 4)
            if mapped is not None and not PORT.same_shape(mapper, address, mapped, 16):
                mapped, method = None, "rejected"
        else:
            mapped, method = mapper.map(address, "data")
        if mapped is None:
            unmapped.append(f"{address:08X} ({'code' if is_code else 'data'}, {method})")
        else:
            rows.append(f"    {{0x{address:08X}u, 0x{mapped:08X}u}},  // {'code' if is_code else 'data'}: {method}")
    if unmapped:
        print("unmapped FH1_ADDR uses:\n  " + "\n  ".join(unmapped), file=sys.stderr)
        return 1
    text = ("// Generated by tools/generate-fh1-v4-addresses.py; do not edit.\n"
            "// Base-disc (0.0.0.10) guest addresses used through FH1_ADDR and their\n"
            "// verified FH1 v4 title-update counterparts.\n" + "\n".join(rows) + "\n")
    if args.check:
        return 0 if OUTPUT.is_file() and OUTPUT.read_text(encoding="utf-8") == text else 1
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"{len(rows)} addresses written to {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
