#!/usr/bin/env python3
"""Port the base-disc ReXGlue analysis files to the FH1 v4 title update.

Reads config/rexglue/analysis/*.toml and writes config/rexglue/analysis-v4/
with every guest address remapped by tools/map-fh1-v4-addresses.py.
Comments and ordering are kept. Manually researched addresses come from
config/rexglue/analysis-v4/overrides.toml ([module] tables of "base" = v4).
An entry whose address cannot be mapped is written commented out with an
`# UNMAPPED` marker and listed in the report; the command then exits 1, so a
v4 build never silently loses a hook.

Images: .local/game/v4-images/<module>.base.bin and .v4.bin, produced with
`pinyon_shift_fh1_archive_extract --xex-image <xex> <out> [--apply-patch]`
from .local/game/v4-codegen (base XEX files beside their .xexp patches).
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("v4map", ROOT / "tools/map-fh1-v4-addresses.py")
V4MAP = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(V4MAP)

# analysis file -> (image module, load address)
FILES = {
    "main-xex.toml": ("default", 0x82000000),
    "fh1-post-processing.toml": ("default", 0x82000000),
    "speech-facade.toml": ("SpeechFacade_default", None),
    "xmedia-facade.toml": ("XMediaFacade_default", None),
}
ADDRESS_KEY = re.compile(
    r"^(\s*(?:address|jump_address_on_true|setjmp_address|longjmp_address|memcpy|memmove|memset)\s*=\s*)"
    r"0x([0-9A-Fa-f]{8})(.*)$")
FUNCTION_TABLE = re.compile(r'^\[functions\."([0-9A-Fa-f]{8})"\](.*)$')
HEADER = (
    "# Generated by tools/port-fh1-v4-analysis.py from ../analysis/{name} for the\n"
    "# FH1 v4 title update applied to the USA 0.0.0.10 disc. Edit the base file or\n"
    "# overrides.toml and regenerate; do not edit this copy by hand.\n")


def image_load(data: bytes) -> int:
    pe = int.from_bytes(data[0x3C:0x40], "little")
    return int.from_bytes(data[pe + 0x34:pe + 0x38], "little")  # PE32 ImageBase


def same_shape(mapper, address: int, mapped: int, size: int) -> bool:
    """The instructions at both addresses agree apart from displacements."""
    a, b, n = mapper.base.index(address), mapper.target.index(mapped), size // 4
    if b < 0 or b + n > len(mapper.target.norm):
        return False
    return V4MAP.shape(mapper.base.norm[a:a + n]) == V4MAP.shape(mapper.target.norm[b:b + n]) and \
        mapper.branches_consistent(address, mapped, n)


def blocks(lines: list[str]) -> list[tuple[int, int]]:
    """Split a TOML file into (start, end) line ranges of table entries."""
    starts = [i for i, line in enumerate(lines) if line.startswith("[")]
    ranges = []
    for n, start in enumerate(starts):
        end = starts[n + 1] if n + 1 < len(starts) else len(lines)
        # Trailing comments/blank lines belong to the next entry.
        while end > start + 1 and (not lines[end - 1].strip() or lines[end - 1].lstrip().startswith("#")):
            end -= 1
        ranges.append((start, end))
    return ranges


def port_file(path: Path, mapper, overrides: dict[int, int], report: dict,
              thunks: bool = False) -> str:
    lines = path.read_text(encoding="utf-8").splitlines()
    size_of = {}
    for start, end in blocks(lines):
        match = FUNCTION_TABLE.match(lines[start])
        if match:
            for line in lines[start:end]:
                size = re.match(r"\s*size\s*=\s*(0x[0-9A-Fa-f]+|\d+)", line)
                if size:
                    size_of[start] = int(size.group(1), 0)

    def resolve(address: int, size: int = 4, kind: str = "code") -> tuple[int | None, str]:
        if address in overrides:
            return overrides[address], "override"
        mapped, method = mapper.map(address, kind, size)
        # A function entry is compared over exactly its own range; a hook also
        # covers the instructions after it.
        span = size if kind == "function" else max(size, 16)
        if mapped is not None and not same_shape(mapper, address, mapped, span):
            report["rejected"].append({"file": path.name, "address": f"{address:08X}",
                                       "v4": f"{mapped:08X}", "method": method})
            return None, "rejected"
        return mapped, method

    unmapped_lines, covered_lines = set(), set()
    base_thunks = V4MAP.vcall_thunks(mapper.base) if thunks else {}
    out = list(lines)
    last_address = None
    for start, end in blocks(lines) + [(0, next((s for s, _ in blocks(lines)), len(lines)))]:
        for i in range(start, end):
            line = lines[i]
            table = FUNCTION_TABLE.match(line)
            key = ADDRESS_KEY.match(line)
            if table:
                address = int(table.group(1), 16)
                mapped, method = resolve(address, size_of.get(i, 4), "function")
                report["methods"][method] = report["methods"].get(method, 0) + 1
                if mapped is None and address in base_thunks:
                    # Its v4 counterparts are declared by thunk discovery below;
                    # slot offsets moved, so a one-to-one pairing is ambiguous.
                    report["methods"]["thunk-discovery"] = report["methods"].get("thunk-discovery", 0) + 1
                    covered_lines.update(range(start, end))
                elif mapped is None:
                    unmapped_lines.update(range(start, end))
                    report["unmapped"].append({"file": path.name, "address": f"{address:08X}", "kind": "function"})
                else:
                    out[i] = f'[functions."{mapped:08X}"]{table.group(2)}'
            elif key:
                address = int(key.group(2), 16)
                field = key.group(1).split("=")[0].strip()
                mapped, method = (None, "unmapped")
                if field == "jump_address_on_true" and last_address and last_address[1] is not None:
                    base_hook, v4_hook = last_address
                    delta = address - base_hook
                    window = (address - base_hook) // 4 + 1
                    a = mapper.base.index(base_hook)
                    b = mapper.target.index(v4_hook)
                    if 0 <= delta < 0x400 and mapper.base.norm[a:a + window] == mapper.target.norm[b:b + window]:
                        mapped, method = v4_hook + delta, "relative"
                if mapped is None:
                    mapped, method = resolve(address)
                report["methods"][method] = report["methods"].get(method, 0) + 1
                if field == "address":
                    last_address = (address, mapped)
                if mapped is None:
                    # A hook without its address is dropped whole; a root or
                    # [rexcrt] key only loses its own line.
                    hook = field in ("address", "jump_address_on_true")
                    unmapped_lines.update(range(start, end) if hook else [i])
                    report["unmapped"].append({"file": path.name, "address": f"{address:08X}", "kind": field})
                else:
                    out[i] = f"{key.group(1)}0x{mapped:08X}{key.group(3)}"
    for i in sorted(unmapped_lines):
        out[i] = "# UNMAPPED " + lines[i]
    for i in sorted(covered_lines):
        out[i] = "# THUNK " + lines[i]
    if thunks:
        # v4-only facts (code without a base counterpart) live beside the port.
        out = [re.sub(r"^includes = \[(.*)\]$", r'includes = [\1, "v4-additions.toml"]', line)
               for line in out]
    text = HEADER.format(name=path.name) + "\n".join(out) + "\n"
    keys = re.findall(r'^\[functions\."([0-9A-F]{8})"\]', text, re.M)
    duplicates = sorted({k for k in keys if keys.count(k) > 1})
    if duplicates:
        report["unmapped"].append({"file": path.name, "duplicate_v4_functions": duplicates})
    if thunks:
        declared = {int(k, 16) for k in re.findall(r'^\[functions\."([0-9A-F]{8})"\]', text, re.M)}
        extra = {a: s for a, s in V4MAP.vcall_thunks(mapper.target).items() if a not in declared}
        report["v4_thunks_added"] = len(extra)
        text += ("\n# Virtual-call thunks discovered in the v4 image (vcall_thunks in\n"
                 "# tools/map-fh1-v4-addresses.py). Entries marked THUNK above are covered here.\n")
        for address in sorted(extra):
            text += f'\n[functions."{address:08X}"]\nsize = 0x{extra[address]:02X}\n'
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--images", type=Path, default=ROOT / ".local/game/v4-images")
    parser.add_argument("--source", type=Path, default=ROOT / "config/rexglue/analysis")
    parser.add_argument("--output", type=Path, default=ROOT / "config/rexglue/analysis-v4")
    args = parser.parse_args()
    overrides_path = args.output / "overrides.toml"
    overrides_doc = tomllib.loads(overrides_path.read_text(encoding="utf-8")) if overrides_path.is_file() else {}
    report = {"methods": {}, "unmapped": [], "rejected": [], "functions": {}}
    mappers = {}
    texts = {}
    for name, (module, load) in FILES.items():
        if module not in mappers:
            base = (args.images / f"{module}.base.bin").read_bytes()
            v4 = (args.images / f"{module}.v4.bin").read_bytes()
            load = load or image_load(base)
            mappers[module] = V4MAP.Mapper(V4MAP.Image(base, load), V4MAP.Image(v4, load))
            m = mappers[module]
            report["functions"][module] = {"base": len(m.base.starts), "v4": len(m.target.starts),
                                           "exact": len(m.exact), "anchored": len(m.anchored)}
        overrides = {int(k, 16): int(v, 16) for k, v in overrides_doc.get(module, {}).items()}
        texts[name] = port_file(args.source / name, mappers[module], overrides, report,
                              thunks=name == "main-xex.toml")
    args.output.mkdir(parents=True, exist_ok=True)
    for name, text in texts.items():
        (args.output / name).write_text(text, encoding="utf-8")
    print(json.dumps(report, indent=2))
    return 1 if report["unmapped"] else 0


if __name__ == "__main__":
    sys.exit(main())
